[phases.setup]
nixPkgs = ["python39", "nodejs-18_x", "npm"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd next-app && npm install"
]

[phases.build]
cmds = [
    "cd next-app && npm run build"
]

[start]
cmd = "python web_app.py"
